name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Python Linter
      run: |
        echo "Running flake8..."
        # Recursively find all Python files and lint
        find . -name "*.py" -exec flake8 {} +
        echo "Python lint completed."

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install jshint --global

    - name: Run JS Linter (excluding node_modules)
      run: |
        echo "Running jshint excluding node_modules..."
        find ./server/database -path ./server/database/node_modules -prune -o -name "*.js" -exec jshint {} +
        echo "JavaScript lint completed."
