name: 'Lint and Auto-Fix Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_and_fix_python:
    name: Lint & Auto-Fix Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install flake8 and autopep8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8

      - name: Auto-fix Python Style Issues
        run: |
          echo "Running autopep8 for fixes..."
          find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
          echo "Autopep8 completed."

      - name: Run Python Linter
        run: |
          echo "Running flake8..."
          find . -name "*.py" -exec flake8 {} +
          echo "Python lint completed."

  lint_and_fix_js:
    name: Lint & Auto-Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Prettier
        run: npm install -g prettier

      - name: Auto-fix JS Style Issues
        run: |
          echo "Running prettier to auto-format JavaScript..."
          find ./server/database -path ./server/database/node_modules -prune -o -name "*.js" -exec prettier --write {} +
          echo "Prettier completed."

      - name: Run JS Linter
        run: |
          echo "Running jshint..."
          find ./server/database -path ./server/database/node_modules -prune -o -name "*.js" -exec jshint {} +
          echo "JavaScript lint completed."
